library(shiny)
library(shinythemes)

navbarPage("Shiny Introduction", theme=shinytheme("paper"),
           tabPanel("What is Shiny?",
                    fluidRow(
                        column(2,
                               HTML('<center><img src="shiny_logo.png"></center>')),
                        column(9, offset=1,
                               titlePanel("Shiny"),
                               tags$b(" - R을 이용한 웹 어플리케이션 프레임워크"),
                               br(),
                               br(),
                               tags$b(" - 반응성(reactivity) 모드를 디폴트로 사용하여 사용자가 입력한 값에 즉각적으로 반응"),
                               hr(),
                               h4("Code structure:"),
                               verbatimTextOutput("well"),
                               tags$b(" - UI : 브라우저를 통해 사용자와 소통하는 부분"),
                               br(),
                               br(),
                               tags$b(" - Server : 사용자가 입력한 값을 가지고 실제 계산이 이루어지는 부분"),
                               br(),
                               br(),
                               tags$b(" - shinyApp() : UI 코드와 서버 코드를 묶어서 실행하고, 샤이니 객체 반환환"))
                    )),
           
           tabPanel("Widgets",
                    navlistPanel("Widgets",
                                 tabPanel("Basic",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Text",
                                                               br(),
                                                               textInput("text", "input text:", value="Enter the text"),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("textOut")))),
                                                      tabPanel("Numeric",
                                                               br(),
                                                               numericInput("num", "input number:", value=10, min=1, max=50),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("numOut")))))),
                                 tabPanel("Slider",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Basic",
                                                               br(),
                                                               sliderInput("slide1", "basic slider:", value=500, min=0, max=1000),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide1Out")))),
                                                      tabPanel("Range",
                                                               br(),
                                                               sliderInput("slide2", "range slider:", value=c(400, 600), min=0, max=1000),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide2Out")))),
                                                      tabPanel("Animation",
                                                               br(),
                                                               sliderInput("slide3", "animation slider:", 
                                                                           value=1000, min=0, max=30000, pre="￦", sep=",", step=1000,
                                                                           animate=animationOptions(interval=500, loop=TRUE)),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide3Out")))))),
                                 tabPanel("List",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Select",
                                                               br(),
                                                               selectInput("select", "select:",
                                                                           choices=c("Monday" = "mon",
                                                                                     "Tuesday" = "tue",
                                                                                     "Wednesday" = "wed",
                                                                                     "Thursday" = "thu",
                                                                                     "Friday" = "fri",
                                                                                     "Saturday" = "sat",
                                                                                     "Sunday" = "sun")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("selectOut")))),
                                                      tabPanel("Radio button",
                                                               br(),
                                                               radioButtons("radio", "radio buttons:",
                                                                            choices=c("Beginner", "Intermediate", "Advanced")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("radioOut")))),
                                                      tabPanel("Check box",
                                                               br(),
                                                               checkboxGroupInput("check", "check box:",
                                                                                  choices=c("C", "C++", "Java", "Python", "R",
                                                                                            "Go", "Javascript")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("checkOut")))))),
                                 tabPanel("Others",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Table",
                                                               br(),
                                                               tags$b("mtcars data table:"),
                                                               hr(),
                                                               tableOutput("tableOut")),
                                                      tabPanel("Plot",
                                                               br(),
                                                               tags$b("mtcars plot:"),
                                                               hr(),
                                                               plotOutput("plotOut")),
                                                      tabPanel("Image",
                                                               br(),
                                                               tags$b("R logo image:"),
                                                               hr(),
                                                               fluidRow(
                                                                   column(5, img(src="R_logo.png", width="100%"))
                                                               )))))
                    ),
           
           tabPanel("Reactivity"),
           tabPanel("Layout")
)