library(shiny)

navbarPage("Shiny Introduction", inverse=TRUE,
           tabPanel("What is Shiny?"),
           
           tabPanel("Widgets",
                    navlistPanel("Widgets",
                                 tabPanel("Basic",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Text",
                                                               br(),
                                                               textInput("text", "input text:", value="Enter the text"),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("textOut")))),
                                                      tabPanel("Numeric",
                                                               br(),
                                                               numericInput("num", "input number:", value=10, min=1, max=50),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("numOut")))))),
                                 tabPanel("Slider",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Basic",
                                                               br(),
                                                               sliderInput("slide1", "basic slider:", value=500, min=0, max=1000),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide1Out")))),
                                                      tabPanel("Range",
                                                               br(),
                                                               sliderInput("slide2", "range slider:", value=c(400, 600), min=0, max=1000),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide2Out")))),
                                                      tabPanel("Animation",
                                                               br(),
                                                               sliderInput("slide3", "animation slider:", 
                                                                           value=1000, min=0, max=30000, pre="￦", sep=",", step=1000,
                                                                           animate=animationOptions(interval=500, loop=TRUE)),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("slide3Out")))))),
                                 tabPanel("List",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Select",
                                                               br(),
                                                               selectInput("select", "select:",
                                                                           choices=c("Monday" = "mon",
                                                                                     "Tuesday" = "tue",
                                                                                     "Wednesday" = "wed",
                                                                                     "Thursday" = "thu",
                                                                                     "Friday" = "fri",
                                                                                     "Saturday" = "sat",
                                                                                     "Sunday" = "sun")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("selectOut")))),
                                                      tabPanel("Radio button",
                                                               br(),
                                                               radioButtons("radio", "radio buttons:",
                                                                            choices=c("Beginner", "Intermediate", "Advanced")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("radioOut")))),
                                                      tabPanel("Check box",
                                                               br(),
                                                               checkboxGroupInput("check", "check box:",
                                                                                  choices=c("C", "C++", "Java", "Python", "R",
                                                                                            "Go", "Javascript")),
                                                               hr(),
                                                               fluidRow(column(7, verbatimTextOutput("checkOut")))))),
                                 tabPanel("Others",
                                          tabsetPanel(type="tabs",
                                                      tabPanel("Table",
                                                               br(),
                                                               tags$b("mtcars data table:"),
                                                               hr(),
                                                               tableOutput("tableOut")),
                                                      tabPanel("Plot",
                                                               br(),
                                                               tags$b("mtcars plot:"),
                                                               hr(),
                                                               plotOutput("plotOut")),
                                                      tabPanel("Image",
                                                               br(),
                                                               tags$b("R logo image:"),
                                                               hr(),
                                                               fluidRow(
                                                                   column(5, img(src="R_logo.png", width="100%"))
                                                               )))))
                    ),
           
           tabPanel("Reactivity"),
           tabPanel("Layout")
)